name: CI build

on:
  pull_request:
  push:
    branches:
      - master
      - support/*
  workflow_dispatch:
  workflow_call:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:

  build:
    name: Build on ${{ matrix.os-name }}
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
        include:
          - os: windows
            os-image: windows-2022
            os-name: Windows
            artifact-name: windows-artifacts
            dotnet-versions-to-install: |
              3.1
          - os: ubuntu
            os-image: ubuntu-22.04
            os-name: Ubuntu
            artifact-name: ubuntu-artifacts
            dotnet-versions-to-install: |
              3.1
              2.1
          - os: macos
            os-image: macos-12
            os-name: macOS
            artifact-name: macos-artifacts
            dotnet-versions-to-install: |
              3.1
              2.1
    runs-on: ${{ matrix.os-image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        if: ${{ matrix.dotnet-versions-to-install }}
        with:
          dotnet-version: ${{ matrix.dotnet-versions-to-install }}
      - name: Run build script
        run: ./build.ps1
        shell: pwsh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.artifact-name }}
          path: artifacts/**/*

  build-docs:
    name: Build documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
      - name: Build docs
        run: ./build.ps1 docs
        shell: pwsh
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: artifacts/docs
      - name: Upload link check report
        uses: actions/upload-artifact@v4
        with:
          name: docs-link-check
          path: artifacts/docs-link-check.html
